; PlatformIO Project Configuration File
;
; Color calibration tool for HUB75 P4 64x32 panels
; with DMDos V3 board + ESP32
;
[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
board_build.f_flash = 80000000L
upload_speed = 115200
lib_deps =
    mrfaptastic/ESP32 HUB75 LED MATRIX PANEL DMA Display @ ^3.0.12
    adafruit/Adafruit GFX Library @ ^1.11.9
